/**
 *  class generated for the costCenterApprover web service, to be used by gFRS_CostCenterApprovalWS
 **/

public class gFRS_CostCenterApproverESB {
    public class ApproverHierarchyResponse {
        public gFRS_CostCenterApprovalWS.costCenterApproverResponse_element costCenterApproverResponse;
        
        private String[] costCenterApproverResponse_type_info = new String[]{'costCenterApproverResponse',System.Label.gFRS_WS_ESB_SAP_TYPES,'costCenterApproverResponse_element','1','1','false'};
        private String[] apex_schema_type_info                = new String[]{'http://localhost/GneCOMM_CostCenter/GFRS_O_1_SAP_I_1/Services/costCenterApprover','false','false'};
        private String[] field_order_type_info                = new String[]{'costCenterApproverResponse'};
    }
    public class ApproverHierarchyRequest {
        public gFRS_CostCenterApprovalWS.costCenterApproverRequest_element costCenterApproverRequest;
        
        private String[] costCenterApproverRequest_type_info = new String[]{'costCenterApproverRequest',System.Label.gFRS_WS_ESB_SAP_TYPES,'costCenterApproverRequest_element','1','1','false'};
        private String[] apex_schema_type_info               = new String[]{'http://localhost/GneCOMM_CostCenter/GFRS_O_1_SAP_I_1/Services/costCenterApprover','false','false'};
        private String[] field_order_type_info               = new String[]{'costCenterApproverRequest'};
    }
}