/**********************************************************************************************************************
Purpose: ROBOCOPS-362
This class is used to avoid recursive trigger "SPLOA_Request_HistoryTracker".
=======================================================================================================================
History                                                            
-------                                                            
VERSION  AUTHOR        DATE            DETAIL                       
1.0     Raju Manche  10/9/2020      INITIAL DEVELOPMENT

***********************************************************************************************************************/
public class SPLOA_HelperClass {
    public static boolean firstRun = true;
}