public  class GNE_CM_ICD9_Code_Dictionary {
	public static final String ELIGIBILITY_ELIGIBLE = 'Eligible';
	public static final String ELIGIBILITY_NOT_ELIGIBLE = 'Not Eligible';
	public static final String ELIGIBILITY_MEDICAL_REVIEW = 'Medical Review';
	//public static final String ELIGIBILITY_PENDING_ATTESTATION = 'Pending Attestation';	
	//Need to verify if this should be Pending Eligibility as per the data values 
	public static final String ELIGIBILITY_PENDING_ATTESTATION = 'Pending Eligibility';	
	public static final String ELIGIBILITY_FORBIDDEN = 'Forbidden';
}